keys:
- cipher: chacha20-ietf-poly1305
  id: '1'
  port: 1234
  secret: '12341234'
- cipher: chacha20-ietf-poly1305
  id: '2'
  port: 2345
  secret: '23452345'
- cipher: chacha20-ietf-poly1305
  id: '3'
  port: 3456
  secret: '34563456'
